"""Author original PRISM FALL geometry, surface masks and two new event sounds.

Run inside Unreal Python to import /Game/Aegis/V2 only. Run with ordinary Python
and --source-only to generate deterministic source assets without starting UE.
Use -AegisV2MeshesOnly in Unreal (or --meshes-only outside Unreal) to regenerate
and reimport just the three V2 meshes, preserving all materials/audio/textures.
The six v1.5 sounds/materials are retained and never regenerated by this script.
"""
import array
import hashlib
import json
import math
from pathlib import Path
import random
import struct
import sys
import wave

try:
    import unreal
except ImportError:
    unreal = None


def outward(vertices, face):
    a, b, c = [vertices[i] for i in face[:3]]
    u, v = [b[i]-a[i] for i in range(3)], [c[i]-a[i] for i in range(3)]
    n = [u[1]*v[2]-u[2]*v[1], u[2]*v[0]-u[0]*v[2], u[0]*v[1]-u[1]*v[0]]
    center = [sum(vertices[j][i] for j in face)/len(face) for i in range(3)]
    if sum(x*y for x,y in zip(n, center)) < 0:
        face = list(reversed(face)); n = [-x for x in n]
    length = math.sqrt(sum(x*x for x in n))
    return face, [x/max(length,1e-8) for x in n]


def mesh_source(path, vertices, faces):
    rows = ['# Original Aegis PRISM FALL source mesh; centimetres, Z-up, flat facets.', 's off']
    rows += ['v %.6f %.6f %.6f' % tuple(v) for v in vertices]
    # Each polygon has its own planar UV island. A four-corner wrap would repeat
    # UVs on the octagonal armor caps and make several fan triangles degenerate.
    polygons = []
    normals = []
    uv_count = 0
    for face in faces:
        face, normal = outward(vertices, face)
        origin = vertices[face[0]]
        edge = [vertices[face[1]][i] - origin[i] for i in range(3)]
        length = math.sqrt(sum(v*v for v in edge))
        assert length > 1e-8, 'Mesh face has a zero-length first edge'
        axis_u = [v/length for v in edge]
        axis_v = [normal[1]*axis_u[2]-normal[2]*axis_u[1],
                  normal[2]*axis_u[0]-normal[0]*axis_u[2],
                  normal[0]*axis_u[1]-normal[1]*axis_u[0]]
        points = [[sum((vertices[index][i]-origin[i])*axis[i] for i in range(3))
                   for axis in (axis_u,axis_v)] for index in face]
        low = [min(p[i] for p in points) for i in range(2)]
        span = [max(p[i] for p in points)-low[i] for i in range(2)]
        assert min(span) > 1e-8, 'Mesh face cannot be projected to a UV plane'
        uv = [[(p[i]-low[i])/span[i] for i in range(2)] for p in points]
        # Verify the actual six-decimal coordinates written to OBJ, not just the
        # source doubles. This fails source generation before importing bad UVs.
        uv = [[round(value, 6) for value in point] for point in uv]
        for j in range(1,len(face)-1):
            a,b,c = uv[0],uv[j],uv[j+1]
            area = (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])
            assert abs(area) > 1e-8, 'Degenerate UV triangle in generated mesh'
        rows += ['vt %.6f %.6f' % tuple(point) for point in uv]
        polygons.append((face,uv_count))
        normals.append(normal)
        uv_count += len(face)
    rows += ['vn %.6f %.6f %.6f' % tuple(normal) for normal in normals]
    for i,(face,offset) in enumerate(polygons):
        for j in range(1,len(face)-1):
            rows.append('f ' + ' '.join(f'{face[k]+1}/{offset+k+1}/{i+1}' for k in (0,j,j+1)))
    path.write_text('\n'.join(rows)+'\n',encoding='ascii')


def crystal(sides=6):
    vertices=[]
    for z, radius, twist in [(-48,21,0),(-23,38,0),(20,32,.07)]:
        vertices += [(math.cos(i*math.tau/sides+twist)*radius,
                      math.sin(i*math.tau/sides+twist)*radius,z) for i in range(sides)]
    vertices += [(8,-4,70),(0,0,-58)]
    faces=[]
    for ring in range(2):
        for i in range(sides):
            j=(i+1)%sides
            faces.append([ring*sides+i,ring*sides+j,(ring+1)*sides+j,(ring+1)*sides+i])
    for i in range(sides):
        j=(i+1)%sides
        faces += [[2*sides+i,2*sides+j,3*sides],[j,i,3*sides+1]]
    return vertices,faces


def armor():
    profile=[(-30,-50),(30,-50),(50,-30),(50,30),(30,50),(-30,50),(-50,30),(-50,-30)]
    vertices=[(x,y*scale,z*scale) for x,scale in [(-50,.82),(-34,1),(28,1),(50,.66)] for y,z in profile]
    faces=[list(range(8)),list(range(24,32))]
    for ring in range(3):
        for i in range(8):
            j=(i+1)%8; faces.append([ring*8+i,ring*8+j,(ring+1)*8+j,(ring+1)*8+i])
    return vertices,faces


def pylon():
    vertices=[]
    for z,r,angle in [(-50,50,0),(-32,43,0),(32,31,.13),(50,25,.13)]:
        vertices += [(math.cos(i*math.pi/3+angle)*r,math.sin(i*math.pi/3+angle)*r,z) for i in range(6)]
    faces=[list(range(6)),list(range(18,24))]
    for ring in range(3):
        for i in range(6):
            j=(i+1)%6; faces.append([ring*6+i,ring*6+j,(ring+1)*6+j,(ring+1)*6+i])
    return vertices,faces


def write_mask(path):
    size=256; rng=random.Random(2018)
    pixels=[]
    scratches=[(rng.randrange(size),rng.randrange(size),rng.randrange(9,45)) for _ in range(80)]
    for y in range(size):
        row=bytearray()
        for x in range(size):
            noise=rng.randrange(-12,13)
            # Broad worn patches and narrow authored scratches, no external art.
            field=math.sin(x*.055+math.sin(y*.041))*math.cos(y*.037)
            value=int(max(24,min(242,150+field*38+noise)))
            if any(abs(x-sx)<1 and (y-sy)%size < length for sx,sy,length in scratches): value=232
            rough=int(max(40,min(245,200-field*24-noise)))
            row += bytes((value,rough,value))
        pixels.append(row)
    image=b''.join(reversed(pixels))
    header=b'BM'+struct.pack('<IHHI',54+len(image),0,0,54)
    dib=struct.pack('<IIIHHIIIIII',40,size,size,1,24,0,len(image),2835,2835,0,0)
    path.write_bytes(header+dib+image)


def synthesize_audio(folder):
    folder.mkdir(parents=True,exist_ok=True)
    for name,duration in [('S_Charge',.44),('S_Overclock',1.15)]:
        rate=48000; rng=random.Random('prism-fall/'+name); values=array.array('h')
        for i in range(round(duration*rate)):
            t=i/rate; u=t/duration; attack=min(1,t/.004)
            if name=='S_Charge':
                # Successful charged-shot discharge: impact body + decaying glass partials.
                body=math.sin(math.tau*(170*t-110*t*t))*math.exp(-t*17)
                glass=sum(math.sin(math.tau*f*t)*math.exp(-t*d) for f,d in [(1320,15),(2147,21),(3260,27)])/3
                noise=rng.uniform(-1,1)*math.exp(-t*40)
                value=(.54*body+.24*glass+.18*noise)*attack*(1-u)
            else:
                # Target overclock accepted: ascending arpeggio + resonant core, no loop.
                value=0
                for k,f in enumerate([196,293.66,392,587.33,783.99]):
                    dt=t-k*.085
                    if dt>=0:value+=math.sin(math.tau*f*dt)*math.exp(-dt*5)*.12
                value=(value+.13*math.sin(math.tau*65*t)*math.exp(-t*3))*attack*(1-u)
            values.append(round(max(-.8,min(.8,value))*32767))
        with wave.open(str(folder/(name+'.wav')),'wb') as stream:
            stream.setnchannels(1);stream.setsampwidth(2);stream.setframerate(rate);stream.writeframes(values.tobytes())


def import_assets(root, source, audio, meshes_only=False):
    library=unreal.EditorAssetLibrary; tools=unreal.AssetToolsHelpers.get_asset_tools(); edit=unreal.MaterialEditingLibrary
    base='/Game/Aegis/V2'
    tasks=[]
    for path in sorted(source.glob('*.obj')):
        task=unreal.AssetImportTask()
        task.set_editor_property('filename',str(path));task.set_editor_property('destination_path',base+'/Meshes')
        task.set_editor_property('destination_name',path.stem);task.set_editor_property('automated',True)
        task.set_editor_property('save',True);task.set_editor_property('replace_existing',True)
        options=unreal.FbxImportUI()
        options.set_editor_property('import_mesh',True);options.set_editor_property('import_materials',False)
        options.set_editor_property('import_textures',False);options.set_editor_property('import_as_skeletal',False)
        options.set_editor_property('mesh_type_to_import',unreal.FBXImportType.FBXIT_STATIC_MESH)
        data=options.get_editor_property('static_mesh_import_data')
        data.set_editor_property('combine_meshes',True);data.set_editor_property('auto_generate_collision',False)
        data.set_editor_property('convert_scene',False)
        data.set_editor_property('normal_import_method',unreal.FBXNormalImportMethod.FBXNIM_IMPORT_NORMALS)
        task.set_editor_property('options',options);task.set_editor_property('factory',unreal.FbxFactory())
        tasks.append(task)
    extra_assets = [] if meshes_only else [(source/'T_V2Surface.bmp',base+'/Textures')]+[(p,base+'/Audio') for p in sorted(audio.glob('*.wav'))]
    for path,dest in extra_assets:
        task=unreal.AssetImportTask();task.set_editor_property('filename',str(path));task.set_editor_property('destination_path',dest)
        task.set_editor_property('automated',True);task.set_editor_property('save',True);task.set_editor_property('replace_existing',True);tasks.append(task)
    tools.import_asset_tasks(tasks)
    if meshes_only:
        for name in ('SM_V2Shard','SM_V2Armor','SM_V2Pylon'):
            assert library.does_asset_exist(base+'/Meshes/'+name),name
        unreal.log('AEGIS_V2_MESHES_COMPLETE meshes=3 planar_uv=1 materials_untouched=1 audio_untouched=1')
        return
    texture=unreal.load_asset(base+'/Textures/T_V2Surface')
    assert texture,'V2 surface texture was not imported'
    texture.set_editor_property('srgb',False)
    library.save_loaded_asset(texture)
    for name,metal,rough,glow in [('M_V2Basalt',.12,.82,.0),('M_V2Ceramic',.42,.44,.025),('M_V2Crystal',.26,.23,.24),('M_V2Energy',.0,.4,1.65)]:
        path=base+'/Materials/'+name
        mat=unreal.load_asset(path) if library.does_asset_exist(path) else tools.create_asset(name,base+'/Materials',unreal.Material,unreal.MaterialFactoryNew())
        edit.delete_all_material_expressions(mat)
        mat.set_editor_property('used_with_instanced_static_meshes',True)
        def expr(kind,x,y):return edit.create_material_expression(mat,kind,x,y)
        def constant(value,x,y):
            node=expr(unreal.MaterialExpressionConstant,x,y);node.set_editor_property('r',value);return node
        def connect(a,out,b,input_name):edit.connect_material_expressions(a,out,b,input_name)
        tint=expr(unreal.MaterialExpressionVectorParameter,-800,0);tint.set_editor_property('parameter_name','Tint')
        tint.set_editor_property('default_value',unreal.LinearColor(.16,.25,.30,1))
        tex=expr(unreal.MaterialExpressionTextureSample,-800,240);tex.set_editor_property('texture',texture)
        tex.set_editor_property('sampler_type',unreal.MaterialSamplerType.SAMPLERTYPE_LINEAR_COLOR)
        uv=expr(unreal.MaterialExpressionTextureCoordinate,-1050,240);uv.set_editor_property('u_tiling',2.0);uv.set_editor_property('v_tiling',2.0)
        connect(uv,'',tex,'Coordinates')
        variation=expr(unreal.MaterialExpressionMultiply,-500,200);connect(tex,'R',variation,'A');connect(constant(.25,-800,440),'',variation,'B')
        base_level=expr(unreal.MaterialExpressionAdd,-300,200);connect(variation,'',base_level,'A');connect(constant(.73,-500,440),'',base_level,'B')
        color=expr(unreal.MaterialExpressionMultiply,-70,0);connect(tint,'',color,'A');connect(base_level,'',color,'B')
        edit.connect_material_property(color,'',unreal.MaterialProperty.MP_BASE_COLOR)
        edit.connect_material_property(constant(metal,-70,280),'',unreal.MaterialProperty.MP_METALLIC)
        edit.connect_material_property(constant(rough,-70,380),'',unreal.MaterialProperty.MP_ROUGHNESS)
        emission=expr(unreal.MaterialExpressionMultiply,-70,-170);connect(tint,'',emission,'A')
        if name=='M_V2Crystal':
            fresnel=expr(unreal.MaterialExpressionFresnel,-580,-230)
            lift=expr(unreal.MaterialExpressionAdd,-340,-200);connect(fresnel,'',lift,'A');connect(constant(glow,-580,-400),'',lift,'B');connect(lift,'',emission,'B')
        else:connect(constant(glow,-340,-300),'',emission,'B')
        edit.connect_material_property(emission,'',unreal.MaterialProperty.MP_EMISSIVE_COLOR)
        edit.recompile_material(mat);assert library.save_loaded_asset(mat)
    expected=['Meshes/SM_V2Shard','Meshes/SM_V2Armor','Meshes/SM_V2Pylon','Textures/T_V2Surface',
              'Materials/M_V2Basalt','Materials/M_V2Ceramic','Materials/M_V2Crystal','Materials/M_V2Energy',
              'Audio/S_Charge','Audio/S_Overclock']
    for asset in expected:assert library.does_asset_exist(base+'/'+asset),asset
    unreal.log('AEGIS_V2_ASSETS_COMPLETE meshes=3 materials=4 texture=1 new_sounds=2 original_synthesis=1')


def main():
    root=Path(unreal.Paths.project_dir()).resolve() if unreal else Path(__file__).resolve().parents[2]
    meshes_only = '--meshes-only' in sys.argv or bool(unreal and '-aegisv2meshesonly' in unreal.SystemLibrary.get_command_line().lower().split())
    source=root/'Saved/V2AssetSource'; source.mkdir(parents=True,exist_ok=True)
    audio=root/'assets/v2_source_audio'
    for name,data in [('SM_V2Shard',crystal()),('SM_V2Armor',armor()),('SM_V2Pylon',pylon())]:mesh_source(source/(name+'.obj'),*data)
    if not meshes_only:
        write_mask(source/'T_V2Surface.bmp');synthesize_audio(audio)
    generated = list(source.glob('*.obj'))
    if not meshes_only: generated += list(source.glob('*.bmp'))+list(audio.glob('*.wav'))
    manifest={'description':'Original deterministic PRISM FALL source assets; per-face planar UVs; no external media.',
              'meshesOnly':meshes_only,
              'files':{str(p.relative_to(root)):{'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(generated)}}
    manifest_path=source/('mesh-source-manifest.json' if meshes_only else 'source-manifest.json')
    manifest_path.write_text(json.dumps(manifest,indent=2),encoding='utf-8')
    if unreal:import_assets(root,source,audio,meshes_only=meshes_only)
    else:
        assert '--source-only' in sys.argv,'Use --source-only outside Unreal; no engine is launched by this script.'
        print(json.dumps({'sourceOnly':True,'meshesOnly':meshes_only,'manifest':str(manifest_path),'originalFiles':len(manifest['files'])}))


if __name__=='__main__':main()
