"""Compose an honest Chinese portfolio film from one complete native capture.

Final delivery requires consecutive, native 30 fps frames and engine sound events.
--preview permits explicitly labelled sparse, silent development captures only.
No gameplay frame is cropped, interpolated, reordered, or generated by this script.
"""
from __future__ import annotations

import argparse
from bisect import bisect_right
from fractions import Fraction
import hashlib
import json
import math
from pathlib import Path
import re
import subprocess
import time
import wave

import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FFMPEG = Path('D:/AegisWork/Tools/decision-video/imageio_ffmpeg/binaries/ffmpeg-win-x86_64-v7.1.exe')
FPS, RATE, INTRO, END = 30, 48000, 5, 7
NAVY, PANEL, WHITE, MUTED, MINT, AMBER = '#102530', '#193440', '#edf2ef', '#a2b5ba', '#70dfc3', '#edbb70'


def sha(path):
    h = hashlib.sha256()
    with Path(path).open('rb') as f:
        for block in iter(lambda: f.read(1024 * 1024), b''):
            h.update(block)
    return h.hexdigest()


def strict_json(path):
    def pairs(rows):
        result = {}
        for key, value in rows:
            if key in result:
                raise ValueError(f'duplicate JSON key: {key}')
            result[key] = value
        return result
    return json.loads(Path(path).read_text(encoding='utf-8-sig'), object_pairs_hook=pairs,
                      parse_constant=lambda x: (_ for _ in ()).throw(ValueError(f'non-finite JSON: {x}')))


def finite(value, label):
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value):
        raise ValueError(f'{label} must be finite')
    return float(value)


def require(condition, message):
    if not condition:
        raise ValueError(message)


def validate_capture(capture, preview=False):
    require(capture.get('validRun') is True, 'capture did not pass native completion')
    require(capture.get('scriptedPlayer') is True and capture.get('fixtureDamage') is False
            and capture.get('humanPlaytest') is False, 'unsupported input/provenance flags')
    require(capture.get('outcome') in ('won', 'lost'), 'capture has no natural outcome')
    rows = capture.get('frameTimes', [])
    require(len(rows) >= 2 and capture.get('frames') == len(rows) == capture.get('completedFrames'),
            'missing or incomplete native frames')
    times = [finite(row['videoSeconds'], 'frame time') for row in rows]
    require(times[0] >= 0, 'negative frame time')
    deltas = [b-a for a, b in zip(times, times[1:])]
    require(all(d > 0 for d in deltas), 'frame times are not strictly increasing')
    interval = deltas[0]
    require(all(abs(d-interval) < 1e-5 for d in deltas), 'native frame intervals are irregular')
    if not preview:
        require(abs(interval - 1/FPS) < 1e-5, 'final film requires native 1/30 second frame spacing')
    else:
        require(abs(interval*FPS-round(interval*FPS)) < 1e-4, 'preview interval must map exactly to 30 fps')
    for index, row in enumerate(rows):
        require(row['file'] == f'frame-{index:06d}.png', 'frame order/path is not canonical')
        finite(row['worldSeconds'], 'world time')
    world = [r['worldSeconds'] for r in rows]
    require(all(b+1e-7 >= a for a, b in zip(world, world[1:])), 'world time runs backwards')
    # Pauses may freeze world time, but the film clock continues at native cadence.
    require(all((b-a) <= interval+1e-4 for a, b in zip(world, world[1:])), 'world time exceeds capture cadence')
    samples = capture.get('samples', [])
    require(samples, 'missing actual phase samples')
    sample_times = [finite(s['videoSeconds'], 'sample time') for s in samples]
    require(all(b >= a for a, b in zip(sample_times, sample_times[1:])), 'sample clock runs backwards')
    for s in samples:
        require(s.get('phase') in range(5) and s.get('wave') in range(4), 'unknown native phase/wave')
        require(isinstance(s.get('diagnostics'), bool), 'missing diagnostic state')
    audio = capture.get('audioEvents', [])
    require(preview or bool(audio), 'final film requires genuine engine audioEvents')
    previous = -1.0
    for event in audio:
        t = finite(event['videoSeconds'], 'audio time')
        require(previous <= t <= times[-1]+interval+.1 and t >= 0, 'audio event clock is invalid')
        previous = t
        require(re.fullmatch(r'S_[A-Za-z0-9_]+', event['asset']) is not None, 'unsafe sound asset name')
        require(0 <= finite(event['volume'], 'sound volume') <= 4, 'invalid sound volume')
        require(len(event['location']) == 3, 'missing actual sound location')
        for coordinate in event['location']:
            finite(coordinate, 'sound location')
        finite(event['worldSeconds'], 'audio world time')
    return interval


def chapter_key(sample):
    phase, stage = sample['phase'], sample['wave']
    if phase == 0:
        return 'briefing'
    if phase in (3, 4):
        return 'result'
    if phase == 2:
        return f'upgrade{stage}'
    if sample['diagnostics']:
        return 'diagnostics'
    return f'stage{stage}'


def validate_ledger(ledger, capture):
    require(ledger.get('ledgerBalanced') is True and ledger.get('traceComplete') is True
            and ledger.get('completed') is True, 'system ledger is incomplete')
    require(ledger['outcome'] == capture['outcome'], 'system and capture outcomes disagree')
    integer_fields = ('energyInitial','energyFinal','energyEarned','energySpent','energyOverflow',
                      'pulsesUsed','repairsUsed','enemiesRewarded','stagesRewarded','eventCount','upgradeMask')
    for key in integer_fields:
        require(type(ledger.get(key)) is int and ledger[key] >= 0, f'invalid ledger counter: {key}')
    for key in ('trialElapsedSeconds','repairPlayerActualHealing','repairCompanionActualHealing',
                'alliedActualDamageDealt','playerActualDamageTaken','companionActualDamageTaken'):
        require(finite(ledger[key], key) >= 0, f'negative ledger value: {key}')
    require(ledger['energyInitial']+ledger['energyEarned']-ledger['energySpent']==ledger['energyFinal'], 'unbalanced energy ledger')
    require(ledger['energySpent']==ledger['pulsesUsed']*35+ledger['repairsUsed']*40, 'spend does not match actual actions')
    require(ledger['energyEarned']+ledger['energyOverflow']==ledger['enemiesRewarded']*12+ledger['stagesRewarded']*25,
            'income does not match kill and stage rewards')
    require(0 <= ledger['energyFinal'] <= 100 and 0 <= ledger['stagesRewarded'] <= 3, 'invalid resource/stage range')
    require(capture['outcome'] != 'won' or ledger['stagesRewarded'] == 3, 'won without three completed stages')


def chapters(capture, interval):
    rows, samples = capture['frameTimes'], capture['samples']
    times = [s['videoSeconds'] for s in samples]
    result = []
    # Decide changes on actual source frames. One source frame always remains one
    # source frame in final mode; sparse previews are explicitly duplicated.
    for i, row in enumerate(rows):
        sample = samples[max(0, bisect_right(times, row['videoSeconds'])-1)]
        key = chapter_key(sample)
        if not result or result[-1]['key'] != key:
            result.append({'key': key, 'firstSourceFrame': i, 'start': i*interval})
    duration = len(rows)*interval
    for i, chapter in enumerate(result):
        chapter['duration'] = (result[i+1]['start'] if i+1 < len(result) else duration)-chapter['start']
    return result


COPY = {
    'briefing': ('行动简报', '把系统取舍放进一次完整行动', [
        ('阶段目标', '占领单个中继 → 连结两个中继 → 清敌撤离。阶段目标推动玩家改变站位。'),
        ('共享资源', '初始能量 60，上限 100。击杀 +12，阶段完成 +25；溢出不会存入储备。'),
        ('游玩范围', '真实关卡、真实规则，由脚本输入操作。本片不是人工可用性测试。')]),
    'stage1': ('01 / 占领', '战斗与占圈，争夺同一段时间', [
        ('推进条件', '敌人进入圈内会阻断进度。至少一名队员占圈；玩家与同伴同时在圈时，速率 ×1.5。'),
        ('Q / 35 能量', '脉冲造成范围伤害并打断敌人。有限范围与视线检查限制覆盖范围。'),
        ('E / 40 能量', '修复自身与近处存活同伴。缺少合法缺血目标时，不花能量、不启动冷却。')]),
    'stage2': ('02 / 转移', '从单点守住，转为路线协作', [
        ('连续两处中继', '占领顺序让移动与火力重新分配。先处理争夺，再决定何时转移。'),
        ('指挥同伴', 'Z 跟随保护 / X 聚焦可见威胁 / C 集结到信号。指令仍受当前视线与路径约束。'),
        ('即时反馈', '角色血条、射击预警、真实命中反馈与资源回执，帮助玩家判断下一步。')]),
    'stage3': ('03 / 撤离', '收束目标，完成整段行动', [
        ('撤离门槛', '先消灭最后的敌人，再由玩家本人进入撤离圈。同伴不能独自完成撤离。'),
        ('保留选择压力', '射击不消耗共享能量；脉冲控制与主动修复竞争同一储备。升级改变使用时机。'),
        ('信息边界', '战斗 UI 不透视敌方状态。YOU 标记只帮助辨认被掩体挡住的玩家自身。')]),
    'upgrade1': ('阶段间 / 升级选择', '三个机制方向，不只是数值加成', [
        ('穿透弹', '基础射击最多命中两个敌人。墙壁与友军仍阻断；通过选角度提高收益。'),
        ('救援脉冲', 'Q 保留控制与伤害，同时恢复自身和近处同伴。一次资源支出兼顾两种用途。'),
        ('生命链接', '真实团队伤害按比例回流为治疗。鼓励持续输出；不复活已倒下的角色。')]),
    'upgrade2': ('阶段间 / 第二次升级', '让既有选择构成自己的打法', [
        ('本局永久保留', '已安装的升级不能重复消耗机会。两次选择构成一套行动配置。'),
        ('支出与时机', '穿透弹不额外耗能；救援脉冲复用 Q 的 35 能量；生命链接按实际伤害结算。'),
        ('清楚呈现代价', '卡片分别说明效果、使用条件与适合打法；此处是原生游戏升级界面。')]),
    'diagnostics': ('F1 / 真实诊断', '正式体验与调试证据分开', [
        ('当前控制路径', '本模式使用战术控制器。右侧原生面板明确说明：Utility 分数不控制当前行为。'),
        ('不冒充 EQS', '此战术移动路径没有使用 EQS；不把其他模式的分数或候选点冒充当前决策。'),
        ('可核对的数据', '展示真实视线 / 记忆 / 预警状态、移动请求、射击次数与能量收支。')]),
    'result': ('行动结算', '把体验结果落到可核对的数据', [
        ('真实运行结果', '原生结算给出阶段、输出、承伤、能量花费与实际修复量。数字来自本次运行。'),
        ('保留完整流程', '从简报、战斗、两次升级到终局连续呈现；没有剪掉失败镜头或重排战斗。'),
        ('证据边界', '这是一局系统展示，不代表平衡性已被证明，也不替代人工试玩。')]),
}


class Editorial:
    def __init__(self, font_dir, preview, has_audio=False):
        self.regular = Path(font_dir)/'msyh.ttc'
        self.bold = Path(font_dir)/'msyhbd.ttc'
        require(self.regular.is_file() and self.bold.is_file(), 'Microsoft YaHei fonts unavailable')
        self.preview = preview
        self.has_audio = has_audio

    def font(self, size, bold=False):
        return ImageFont.truetype(str(self.bold if bold else self.regular), size)

    def text(self, d, xy, text, size, color=WHITE, bold=False):
        d.text(xy, text, font=self.font(size, bold), fill=color, stroke_width=0)

    def wrap(self, d, xy, text, width, size, color=MUTED, spacing=12):
        x, y = xy
        row = ''
        font = self.font(size)
        for char in text:
            if row and d.textlength(row+char, font=font) > width and char not in '，。；：！？、）】':
                d.text((x, y), row, font=font, fill=color)
                y += size+spacing
                row = ''
            row += char
        if row:
            d.text((x, y), row, font=font, fill=color)
        return y+size+spacing

    def base(self):
        im = Image.new('RGB', (1920, 1080), NAVY)
        d = ImageDraw.Draw(im)
        for x in range(30, 1920, 70):
            d.line((x, 0, x+220, 1080), fill='#142c37', width=1)
        d.rectangle((40, 36, 47, 105), fill=MINT)
        return im, d

    def footer(self, d):
        self.text(d, (40, 998), '真实关卡连续画面  ·  脚本输入驱动  ·  未修改生命 / 伤害 / AI 规则', 21, MUTED)
        note = ('抽帧预览；真实引擎事件离线重混音频，非最终 30fps 录制' if self.has_audio else
                '抽帧静音预览；非最终 30fps 录制') if self.preview else '固定游戏时钟 30fps 采集，非硬件性能测试；音效为真实引擎事件离线重混，非回环录音'
        self.text(d, (40, 1035), note, 19, AMBER if self.preview else MUTED)

    def chapter(self, key, destination):
        title, subtitle, sections = COPY[key]
        im, d = self.base()
        self.text(d, (68, 33), 'AEGIS ARENA', 44, WHITE, True)
        self.text(d, (426, 48), 'PRISM RELAY  /  系统／综合策划作品展示', 25, MINT)
        self.text(d, (1160, 46), title, 29, WHITE, True)
        d.rectangle((38, 148, 1482, 962), outline='#5b8987', width=2)
        d.rectangle((1510, 150, 1880, 960), fill=PANEL)
        d.rectangle((1510, 150, 1515, 960), fill=MINT)
        self.wrap(d, (1534, 174), subtitle, 322, 31, WHITE, 13)
        y = 300
        for label, copy in sections:
            d.line((1534, y-15, 1856, y-15), fill='#41616b', width=1)
            self.text(d, (1534, y), label, 24, MINT, True)
            y = self.wrap(d, (1534, y+44), copy, 322, 23, WHITE, 12)+34
        require(y <= 966, f'editorial rail overflow: {key}')
        self.footer(d)
        im.save(destination)

    def intro(self, destination):
        im, d = self.base()
        self.text(d, (76, 64), '作品集导览  /  编辑页，非游戏画面', 26, AMBER)
        self.text(d, (100, 211), 'AEGIS ARENA', 100, WHITE, True)
        self.text(d, (106, 351), 'PRISM RELAY', 43, MINT, True)
        self.text(d, (106, 460), '让阶段目标、团队协作与资源取舍相互作用', 45, WHITE, True)
        self.text(d, (108, 551), '系统／综合策划作品展示  ·  完整可玩闭环  ·  真实运行数据', 29, MUTED)
        for i, (number, label) in enumerate([('03', '连续阶段'), ('02', '升级选择'), ('100', '共享能量上限')]):
            x = 110+i*560
            d.rectangle((x, 671, x+488, 861), fill=PANEL)
            self.text(d, (x+28, 690), number, 65, MINT, True)
            self.text(d, (x+30, 788), label, 29, WHITE)
        self.footer(d)
        im.save(destination)

    def end(self, ledger, destination):
        im, d = self.base()
        self.text(d, (76, 64), '本次运行复盘  /  编辑页，非游戏画面', 26, AMBER)
        self.text(d, (98, 191), '一次完整行动，一组可复核的设计选择。', 59, WHITE, True)
        outcome = '完成撤离' if ledger['outcome'] == 'won' else '行动失败'
        self.text(d, (102, 294), f'{outcome}  ·  {ledger["stagesRewarded"]} / 3 阶段  ·  实际游戏用时 {ledger["trialElapsedSeconds"]:.1f} 秒', 34, MINT)
        values = [('实际团队伤害', f'{ledger["alliedActualDamageDealt"]:.0f}'),
                  ('共享能量支出', str(ledger['energySpent'])),
                  ('脉冲 / 修复次数', f'{ledger["pulsesUsed"]} / {ledger["repairsUsed"]}')]
        for i, (label, value) in enumerate(values):
            x = 104+i*562
            d.rectangle((x, 403, x+510, 615), fill=PANEL)
            self.text(d, (x+28, 431), label, 27, MUTED)
            self.text(d, (x+28, 487), value, 68, WHITE, True)
        self.wrap(d, (106, 687), '设计重点：以占圈与转移组织节奏，以共用能量制造时机取舍，以三种机制升级建立不同打法。', 1660, 33, WHITE, 18)
        scope = '本局未发生成功的主动修复，因此不把它计作已展示分支。' if ledger['repairsUsed'] == 0 else f'主动修复实际恢复 {ledger["repairPlayerActualHealing"]+ledger["repairCompanionActualHealing"]:.0f} HP；只计入 E 的实际治疗。'
        self.text(d, (108, 806), scope, 26, AMBER)
        self.text(d, (108, 867), '范围：单局合成输入实机展示；不是人工试玩结论，也不证明整体平衡或一般 AI 可靠性。', 25, MUTED)
        self.text(d, (108, 923), 'AI 辅助实现与制作；个人职责以设计说明为准。', 22, MUTED)
        self.footer(d)
        im.save(destination)


def mix_audio(events, source_dir, destination, duration, capture_start):
    audio = np.zeros((round(duration*RATE), 2), dtype=np.float32)
    assets = {}
    cache = {}
    for event in events:
        name = event['asset']
        if name not in cache:
            path = source_dir/f'{name}.wav'
            require(path.is_file(), f'original audio asset missing: {name}')
            with wave.open(str(path), 'rb') as w:
                require(w.getsampwidth() == 2 and w.getnchannels() in (1, 2), 'only original PCM16 mono/stereo WAV supported')
                rate, channels = w.getframerate(), w.getnchannels()
                raw = np.frombuffer(w.readframes(w.getnframes()), dtype='<i2').reshape(-1, channels).astype(np.float32)/32768
            if channels == 1:
                raw = np.repeat(raw, 2, axis=1)*np.float32(.70710678)
            if rate != RATE:
                old_t = np.arange(len(raw))/rate
                new_t = np.arange(round(len(raw)*RATE/rate))/RATE
                raw = np.column_stack([np.interp(new_t, old_t, raw[:, c]) for c in range(2)]).astype(np.float32)
            cache[name] = raw
            assets[name] = {'path': str(path.resolve()), 'sha256': sha(path), 'bytes': path.stat().st_size,
                            'sourceSampleRate': rate, 'sourceChannels': channels}
        start = round((INTRO+max(0, event['videoSeconds']-capture_start))*RATE)
        clip = cache[name]
        count = min(len(clip), len(audio)-start)
        require(count > 0, 'audio event falls outside final film')
        audio[start:start+count] += clip[:count]*np.float32(event['volume']*.5)
    peak = float(np.max(np.abs(audio)))
    gain = min(1.0, .82/peak) if peak else 1.0
    pcm = np.rint(audio*gain*32767).astype('<i2')
    with wave.open(str(destination), 'wb') as w:
        w.setnchannels(2); w.setsampwidth(2); w.setframerate(RATE); w.writeframes(pcm.tobytes())
    return {'eventCount': len(events), 'assets': assets, 'sourceGain': .5, 'peakBeforeNormalization': peak,
            'normalizationGain': gain, 'stereoMethod': 'centered source channels; no invented spatial attenuation',
            'sampleRate': RATE, 'channels': 2, 'sha256': sha(destination),
            'method': 'genuine engine-triggered events remixed from original WAVs; not loopback capture'}


def run(command, log):
    with Path(log).open('w', encoding='utf-8') as f:
        result = subprocess.run([str(x) for x in command], stdout=f, stderr=subprocess.STDOUT, timeout=2400)
    require(result.returncode == 0, f'ffmpeg failed; see {log}')


def concat_quote(path):
    return str(Path(path).resolve()).replace('\\', '/').replace("'", "'\\''")


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--capture', type=Path, required=True)
    p.add_argument('--output', type=Path, required=True)
    p.add_argument('--ffmpeg', type=Path, default=DEFAULT_FFMPEG)
    p.add_argument('--font-dir', type=Path, default=Path('C:/Windows/Fonts'))
    p.add_argument('--audio-dir', type=Path, default=ROOT/'assets/source_audio')
    p.add_argument('--preview', action='store_true', help='explicit sparse/silent editorial preview, never a final deliverable')
    p.add_argument('--prepare-only', action='store_true', help='validate and render editorial materials without encoding')
    p.add_argument('--crf', type=int, choices=(20, 22), default=22)
    args = p.parse_args()
    capture_dir, out = args.capture.resolve(), args.output.resolve()
    require(capture_dir != out and capture_dir not in out.parents, 'output must be outside the preserved capture directory')
    out.mkdir(parents=True, exist_ok=False)
    started = time.monotonic()
    report = {'schemaVersion': 1, 'passed': False, 'preview': args.preview,
              'humanPlaytest': False, 'fixtureDamage': False, 'nativeGameplayUncropped': True,
              'gameplayInterpolation': False, 'script': {'path': str(Path(__file__).resolve()), 'sha256': sha(__file__)}}
    try:
        source = capture_dir/'capture.json'
        capture = strict_json(source)
        interval = validate_capture(capture, args.preview)
        provenance = strict_json(capture_dir/'provenance.json')
        require(provenance.get('passed') is True, 'capture wrapper did not pass')
        reports = list((capture_dir/'system').glob('portfolio-*.json'))
        traces = list((capture_dir/'system').glob('portfolio-*.jsonl'))
        require(len(reports) == len(traces) == 1, 'require one exact system ledger and event stream')
        ledger = strict_json(reports[0])
        validate_ledger(ledger, capture)
        require(sorted(f.name for f in (capture_dir/'frames').glob('*.png')) == [r['file'] for r in capture['frameTimes']],
                'extra or missing native PNG frames')
        manifest = []
        native_size = None
        for row in capture['frameTimes']:
            frame = capture_dir/'frames'/row['file']
            with Image.open(frame) as im:
                size = im.size
                im.verify()
            if native_size is None:
                native_size = size
            require(size == native_size and size[0]*9 == size[1]*16, 'native frame dimensions changed or are not 16:9')
            manifest.append({'file': row['file'], 'sha256': sha(frame), 'bytes': frame.stat().st_size,
                             'videoSeconds': row['videoSeconds'], 'worldSeconds': row['worldSeconds']})
        (out/'native-frame-manifest.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')
        events = capture.get('audioEvents', [])
        (out/'audio-events.json').write_text(json.dumps(events, ensure_ascii=False, indent=2), encoding='utf-8')
        duration = len(manifest)*interval
        frame_count = round(duration*FPS)
        segments = chapters(capture, interval)
        art = Editorial(args.font_dir, args.preview, bool(events))
        for key in dict.fromkeys(s['key'] for s in segments):
            art.chapter(key, out/f'chapter-{key}.png')
        art.intro(out/'intro.png'); art.end(ledger, out/'outro.png')
        concat = ''.join(f"file '{concat_quote(out/('chapter-'+s['key']+'.png'))}'\nduration {s['duration']:.9f}\n" for s in segments)
        concat += f"file '{concat_quote(out/('chapter-'+segments[-1]['key']+'.png'))}'\n"
        (out/'backgrounds.txt').write_text(concat, encoding='utf-8')
        total_seconds = INTRO+duration+END
        audio = mix_audio(events, args.audio_dir.resolve(), out/'event-mix.wav', total_seconds, capture['frameTimes'][0]['videoSeconds'])
        input_files = [source, capture_dir/'provenance.json', reports[0], traces[0]]
        report.update(capturePath=str(capture_dir), inputs={str(f): {'sha256': sha(f), 'bytes': f.stat().st_size} for f in input_files},
                      sourceBinary=provenance.get('binary'), knownEngineWarnings=provenance.get('knownEngineWarnings', []),
                      nativeFrameManifestSha256=sha(out/'native-frame-manifest.json'), nativeFrames=len(manifest),
                      nativeSize=native_size, nativeIntervalSeconds=interval, nativeFrameRate=1/interval,
                      nativeGameplaySeconds=duration, introSeconds=INTRO, outroSeconds=END, expectedDurationSeconds=total_seconds,
                      sourceTimestampOrigin=capture['frameTimes'][0]['videoSeconds'], chapters=segments, outcome=ledger['outcome'],
                      fullRunLedger=ledger, audio=audio, audioEventsSha256=sha(out/'audio-events.json'),
                      layout={'output':[1920,1080], 'nativeGameplay':[40,150,1440,810], 'rail':[1510,150,370,810]},
                      fonts={str(f):sha(f) for f in (art.regular, art.bold)}, prepared=True,
                      visualQaRequired='Inspect the five encoded QA images, including native on-screen engine warnings; mechanical gates do not read screen text')
        if args.prepare_only:
            report['encodePending'] = True
        else:
            require(args.ffmpeg.is_file(), 'ffmpeg unavailable')
            video = out/('Aegis-Arena-Portfolio-PREVIEW.mp4' if args.preview else 'Aegis-Arena-Portfolio-v1.5.mp4')
            rate = str(Fraction(1/interval).limit_denominator(1000)) if args.preview else '30'
            # Only sparse previews repeat native frames. The final path never
            # inserts an fps/interpolation filter into the native image sequence.
            native = f'[0:v]scale=1440:810:flags=lanczos,setsar=1,setpts=PTS-STARTPTS' + (',tpad=stop_mode=clone:stop_duration=1,fps=30' if args.preview else '') + '[native]'
            filters = ';'.join([native, '[1:v]fps=30,tpad=stop_mode=clone:stop_duration=1,setpts=PTS-STARTPTS[background]',
                f'[background][native]overlay=40:150:eof_action=repeat,trim=end_frame={frame_count},setpts=PTS-STARTPTS[game]',
                f'[2:v]fps=30,trim=duration={INTRO},setsar=1,setpts=PTS-STARTPTS[intro]',
                f'[3:v]fps=30,trim=duration={END},setsar=1,setpts=PTS-STARTPTS[outro]',
                '[intro][game][outro]concat=n=3:v=1:a=0,format=yuv420p[v]'])
            command = [args.ffmpeg, '-hide_banner', '-y', '-threads', '2', '-filter_complex_threads', '2',
                '-framerate', rate, '-start_number', '0', '-i', capture_dir/'frames/frame-%06d.png',
                '-f', 'concat', '-safe', '0', '-i', out/'backgrounds.txt',
                '-loop', '1', '-framerate', '30', '-i', out/'intro.png',
                '-loop', '1', '-framerate', '30', '-i', out/'outro.png', '-i', out/'event-mix.wav',
                '-filter_complex', filters, '-map', '[v]', '-map', '4:a:0', '-c:v', 'libx264', '-preset', 'medium',
                '-threads', '2', '-crf', str(args.crf), '-pix_fmt', 'yuv420p', '-r', '30', '-fps_mode', 'cfr',
                '-frames:v', str(frame_count+(INTRO+END)*FPS), '-c:a', 'aac', '-b:a', '160k',
                '-movflags', '+faststart', '-shortest', video]
            report.update(ffmpeg={'path':str(args.ffmpeg), 'sha256':sha(args.ffmpeg)}, command=[str(x) for x in command])
            run(command, out/'encode.log')
            require(video.stat().st_size < 300_000_000, 'video exceeds 300 MB delivery limit')
            info = subprocess.run([str(args.ffmpeg), '-hide_banner', '-i', str(video)], capture_output=True, text=True)
            (out/'stream-info.txt').write_text(info.stderr, encoding='utf-8')
            require(re.search(r'Video: h264.*yuv420p.*1920x1080.*30 fps', info.stderr), 'unexpected encoded video format')
            require(re.search(r'Audio: aac.*48000 Hz.*stereo', info.stderr), 'unexpected audio format')
            duration_match = re.search(r'Duration: (\d+):(\d+):(\d+\.\d+)', info.stderr)
            require(duration_match is not None, 'missing muxed duration')
            h,m,s = map(float,duration_match.groups()); encoded_duration=h*3600+m*60+s
            require(abs(encoded_duration-total_seconds)<.15, 'encoded duration does not preserve full run')
            decode_command = [str(args.ffmpeg), '-hide_banner', '-v', 'error', '-threads', '2', '-i', str(video),
                              '-map', '0:v:0', '-map', '0:a:0', '-progress', 'pipe:1', '-nostats', '-f', 'null', '-']
            decoded = subprocess.run(decode_command, capture_output=True, text=True, timeout=1200)
            (out/'full-decode.log').write_text(decoded.stdout+decoded.stderr, encoding='utf-8')
            require(decoded.returncode == 0 and not decoded.stderr.strip(), 'full video/audio decode failed')
            decoded_frames = re.findall(r'^frame=(\d+)', decoded.stdout, re.M)
            require(decoded_frames and int(decoded_frames[-1]) == frame_count+(INTRO+END)*FPS, 'decoded frame count mismatch')
            # Five images are extracted from the encoded delivery, never copied from source.
            chosen = [2.0]
            for wanted in ('stage1','upgrade1','diagnostics'):
                segment = next((s for s in segments if s['key']==wanted), None)
                chosen.append(INTRO+segment['start']+min(1.0,segment['duration']/2) if segment else INTRO+duration*.5)
            chosen.append(total_seconds-3)
            qa=[]
            for i,t in enumerate(chosen):
                dest=out/f'qa-{i+1:02d}.png'
                run([args.ffmpeg,'-hide_banner','-v','error','-threads','2','-ss',f'{t:.6f}','-i',video,
                     '-frames:v','1','-update','1',dest],out/f'qa-{i+1:02d}.log')
                with Image.open(dest) as im: require(im.size==(1920,1080),'QA frame dimensions incorrect')
                qa.append({'file':dest.name,'encodedSeconds':t,'sha256':sha(dest)})
            report.update(passed=True, encodedDurationSeconds=encoded_duration, decodedFrames=int(decoded_frames[-1]),
                          fullDecodePassed=True, video={'file':video.name,'bytes':video.stat().st_size,'sha256':sha(video),
                          'codec':'H.264','audioCodec':'AAC','pixelFormat':'yuv420p','fps':30,'crf':args.crf}, qaFrames=qa)
    except Exception as exc:
        report['failure'] = str(exc)
    finally:
        report['wallSeconds'] = time.monotonic()-started
        (out/'video-provenance.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
    print(json.dumps({k:report[k] for k in ('passed','preview','prepared','encodePending','failure','video','wallSeconds') if k in report},ensure_ascii=False,indent=2))
    return 0 if report['passed'] or (args.prepare_only and report.get('prepared')) else 2


if __name__ == '__main__':
    raise SystemExit(main())
